In [20]:
!touch test.py

In [23]:
%pycat test.py

In [22]:
%%writefile test.py
import numpy as np
print ('Hello')


Overwriting test.py


In [24]:
!python test.py

Hello
Hello again


In [26]:
## Cython process

In [27]:
# Step 1: Put your functions into a .pyx file
# Step 2: Create the setup.py file
# Step 3: Tell Python to build the compiled version of .pyx file

In [28]:
!python setup.py build_ext --inplace

Compiling helloworld.pyx because it changed.
[1/1] Cythonizing helloworld.pyx
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/helloworld.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'helloworld' extension
creating build
creating build/temp.linux-x86_64-3.6
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c helloworld.c -o build/temp.linux-x86_64-3.6/helloworld.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/helloworld.o -o /content/helloworld.cpy

In [30]:
!ls -lah

total 204K
drwxr-xr-x 1 root root 4.0K Jul 28 12:50 .
drwxr-xr-x 1 root root 4.0K Jul 28 12:08 ..
drwxr-xr-x 3 root root 4.0K Jul 28 12:50 build
drwxr-xr-x 1 root root 4.0K Jul 22 16:16 .config
-rw-r--r-- 1 root root 101K Jul 28 12:50 helloworld.c
-rwxr-xr-x 1 root root  58K Jul 28 12:50 helloworld.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root   21 Jul 28 12:47 helloworld.pyx
drwxr-xr-x 2 root root 4.0K Jul 28 12:15 .ipynb_checkpoints
drwxr-xr-x 1 root root 4.0K Jul 10 16:29 sample_data
-rw-r--r-- 1 root root  123 Jul 28 12:48 setup.py
-rw-r--r-- 1 root root   33 Jul 28 12:43 test.md
-rw-r--r-- 1 root root   56 Jul 28 12:39 test.py


In [32]:
import helloworld as hw

In [ ]:
# Exercises 1 and 2

In [41]:
def fib_pp(n):
    """Print the Fibonacci series up to n."""
    a, b = 0, 1
    while b < n:
        print (b,)
        a, b = b, a + b

In [ ]:
%timeit fib_pp(2000)

In [36]:
# Cythonise the fib.pyx
!python setup.py build_ext --inplace

Compiling fib.pyx because it changed.
[1/1] Cythonizing fib.pyx
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/fib.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'fib' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c fib.c -o build/temp.linux-x86_64-3.6/fib.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/fib.o -o /content/fib.cpython-36m-x86_64-linux-gnu.so


In [37]:
!ls

build					    helloworld.pyx
fib.c					    sample_data
fib.cpython-36m-x86_64-linux-gnu.so	    setup.py
fib.pyx					    test.md
helloworld.c				    test.py
helloworld.cpython-36m-x86_64-linux-gnu.so


In [38]:
import fib

In [ ]:
%timeit fib.fib(2000)

In [51]:
## Primes example


In [58]:
def primes_pp(kmax):
    # cdef int n, k, i
    p = [i for i in range(1000)]
    result = []
    if kmax > 1000:
        kmax = 1000
    k = 0
    n = 2
    while k < kmax:
        i = 0
        while i < k and n % p[i] != 0:
            i = i + 1
        if i == k:
            p[k] = n
            k = k + 1
            result.append(n)
        n = n + 1
    return result

In [59]:
%timeit primes_pp(1000)

10 loops, best of 3: 51.2 ms per loop


In [61]:
!python setup.py build_ext --inplace

Compiling primes_pp.pyx because it changed.
[1/1] Cythonizing primes_pp.pyx
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/primes_pp.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'primes_pp' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c primes_pp.c -o build/temp.linux-x86_64-3.6/primes_pp.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/primes_pp.o -o /content/primes_pp.cpython-36m-x86_64-linux-gnu.so


In [62]:
import primes_pp

In [63]:
%timeit primes_pp.primes(1000)

10 loops, best of 3: 28 ms per loop


In [64]:
!python setup.py build_ext --inplace

Compiling primes_td.pyx because it changed.
[1/1] Cythonizing primes_td.pyx
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/primes_td.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'primes_td' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c primes_td.c -o build/temp.linux-x86_64-3.6/primes_td.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/primes_td.o -o /content/primes_td.cpython-36m-x86_64-linux-gnu.so


In [66]:
import primes_td

In [67]:
%timeit primes_td.primes(1000)

100 loops, best of 3: 2.08 ms per loop


In [68]:
## Numba JIT

In [69]:
import numpy as np

In [74]:
def pairwise_python_pp(X, D):
    M = X.shape[0]
    N = X.shape[1]
    for i in range(M):
        for j in range(M):
            d = 0.0
            for k in range(N):
                tmp = X[i, k] - X[j, k]
                d += tmp * tmp
            D[i, j] = np.sqrt(d)
            


In [89]:
from numba import double
from numba.decorators import jit

@jit
def pairwise_python_nb(X, D):
    M = X.shape[0]
    N = X.shape[1]
    for i in range(M):
        for j in range(M):
            d = 0.0
            for k in range(N):
                tmp = X[i, k] - X[j, k]
                d += tmp * tmp
            D[i, j] = np.sqrt(d)



In [73]:
X = np.random.random((1000, 3))
D = np.empty((1000,1000))

In [75]:
%timeit pairwise_python_pp(X, D)

1 loop, best of 3: 3.64 s per loop


In [91]:
%timeit pairwise_python_nb (X, D)

100 loops, best of 3: 4.15 ms per loop


In [92]:
## Numba doesn't understand all python packages

In [93]:
# Pure python
def pandas_ex_pp (a): # Function will not benefit from Numba jit
    df = pd.DataFrame.from_dict(a) # Numba doesn't know about pd.DataFrame
    df += 1                        # Numba doesn't understand what this is
    return df.cov()                # or this!


In [94]:
# Numba version
@jit
def pandas_ex_nb(a): # Function will not benefit from Numba jit
    df = pd.DataFrame.from_dict(a) # Numba doesn't know about pd.DataFrame
    df += 1                        # Numba doesn't understand what this is
    return df.cov()                # or this!

In [95]:
import pandas as pd

In [96]:
x = {'a': [1, 2, 3], 'b': [20, 30, 40]}

In [97]:
%timeit pandas_ex_pp (x)

The slowest run took 40.34 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.2 ms per loop


In [98]:
%timeit pandas_ex_nb (x)

<ipython-input-94-53d6f6404b89>:2: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "pandas_ex_nb" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at <ipython-input-94-53d6f6404b89> (4)

File "<ipython-input-94-53d6f6404b89>", line 4:
def pandas_ex_nb(a): # Function will not benefit from Numba jit
    df = pd.DataFrame.from_dict(a) # Numba doesn't know about pd.DataFrame
    ^

  @jit
/usr/local/lib/python3.6/dist-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "pandas_ex_nb" was compiled in object mode without forceobj=True.

File "<ipython-input-94-53d6f6404b89>", line 3:
@jit
def pandas_ex_nb(a): # Function will not benefit from Numba jit
^

  state.func_ir.loc))
/usr/local/lib/python3.6/dist-packages/numba/object_mode_passes.py:188: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated b

The slowest run took 54.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.22 ms per loop


In [99]:
## Using f2py

In [100]:
!gfortran

gfortran: fatal error: no input files
compilation terminated.


In [102]:
!f2py -c fib1.f -m fib1

running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "fib1" sources
f2py options: []
f2py:> /tmp/tmpmbti80fa/src.linux-x86_64-3.6/fib1module.c
creating /tmp/tmpmbti80fa/src.linux-x86_64-3.6
Reading fortran codes...
	Reading file 'fib1.f' (format:fix,strict)
Post-processing...
	Block: fib1
			Block: fib
Post-processing (stage 2)...
Building modules...
	Building module "fib1"...
		Constructing wrapper function "fib"...
		  fib(a,[n])
	Wrote C/API module "fib1" to file "/tmp/tmpmbti80fa/src.linux-x86_64-3.6/fib1module.c"
  adding '/tmp/tmpmbti80fa/src.linux-x86_64-3.6/fortranobject.c' to sources.
  adding '/tmp/tmpmbti80fa/src.linux-x86_64-3.6' to include_dirs.
copying /usr/local/lib/python3.6/dist-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpmbti80fa/src.linux-x86_64-3.6
c

In [103]:
!ls


build
fib1.cpython-36m-x86_64-linux-gnu.so
fib1.f
fib.c
fib.cpython-36m-x86_64-linux-gnu.so
fib.pyx
helloworld.c
helloworld.cpython-36m-x86_64-linux-gnu.so
helloworld.pyx
primes_pp.c
primes_pp.cpython-36m-x86_64-linux-gnu.so
primes_pp.pyx
primes_td.c
primes_td.cpython-36m-x86_64-linux-gnu.so
primes_td.pyx
sample_data
setup.py
test.md
test.py


In [104]:
import numpy as np
import fib1 as fb

In [105]:
# Find out about the interface to fb.fib
print (fb.fib.__doc__)

fib(a,[n])

Wrapper for ``fib``.

Parameters
----------
a : input rank-1 array('d') with bounds (n)

Other Parameters
----------------
n : input int, optional
    Default: len(a)



In [109]:
a = np.zeros(14, 'd')
fb.fib(a)

In [110]:
print (a)

[  0.   1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233.]


In [111]:
fb.fib(a, 6)

In [112]:
print (a)

[  0.   1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233.]


In [116]:
a1 = np.zeros(8,'d')
fb.fib(a1,3)
print (a1)

[0. 1. 1. 0. 0. 0. 0. 0.]


In [118]:
fb.fib(a1,7)
print (a1)

[0. 1. 1. 2. 3. 5. 8. 0.]
